version: '3.8'

services:
  # --- BACKEND (Laravel) ---
  app:
    build:
      context: ./Project_Laravel
      dockerfile: Dockerfile
    image: laravel_app_image
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./Project_Laravel/src:/var/www
    networks:
      - app-network

  web_server:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80" # Backend chạy port 8000
    volumes:
      - ./Project_Laravel/src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # --- FRONTEND (React) ---
  react_app:
    build:
      context: ./Project_React # Trỏ vào thư mục React
      dockerfile: Dockerfile
    image: react_app_image
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:5173" # Mở port 3000 ở ngoài máy thật (Vite mặc định chạy 5173 bên trong)
    volumes:
      - ./Project_React:/app # Mount code để sửa code là cập nhật liền (Hot reload)
      - /app/node_modules    # Giữ thư viện node_modules riêng cho container
    # Lệnh này quan trọng: --host để Vite chấp nhận kết nối từ bên ngoài container
    command: npm run dev -- --host 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: