version: '3.8'

services:
  # 1. PHP App (Laravel) - Chạy từ Dockerfile ta vừa viết
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www # Mount code vào container
    networks:
      - laravel-net

  # 2. Web Server (Nginx)
  web_server:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nạp cấu hình Nginx
    depends_on:
      - app # Web server phải chờ PHP chạy trước
    networks:
      - laravel-net

  # 3. Database (MySQL)
  database:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    ports:
      - "33060:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge