name: Deploy Laravel to Somee
on:
  push:
    branches:
      - main
    paths:
      - 'Project_Laravel/**' # Chá»‰ cháº¡y khi sá»­a code Laravel

jobs:
  deploy:
    name: ðŸŽ‰ Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Láº¥y code má»›i nháº¥t
        uses: actions/checkout@v4

      # CÃ i Ä‘áº·t thÆ° viá»‡n PHP (Vendor) Ä‘á»ƒ code cháº¡y Ä‘Æ°á»£c ngay
      - name: ðŸ”¨ Install Dependencies
        run: |
          cd Project_Laravel
          composer install --no-dev --optimize-autoloader

      - name: ðŸ“‚ Upload lÃªn Somee qua FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Folder chá»©a code Laravel dÆ°á»›i mÃ¡y báº¡n
          local-dir: ./Project_Laravel/
          
          # Folder Ä‘Ã­ch trÃªn Somee (Láº¥y chÃ­nh xÃ¡c tá»« hÃ¬nh báº¡n gá»­i)
          server-dir: /www.thangdeploy2025.somee.com/
